services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: transcendence-nginx-dev
    ports:
      - "8080:8080"
    depends_on:
      - client
      - server
    volumes:
      - client-build:/usr/share/nginx/html:ro
    networks:
      - transcendence
    restart: unless-stopped

  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile.dev
    container_name: transcendence-server-dev

    expose:
      - "8080"
    ports:
      - "8081:8081"   # sqlite-web port

    volumes:
      - ./server/src:/app/src:ro
      - dev-database:/app/data
      - /app/node_modules

    environment:
      - NODE_ENV=development
      - PORT=8080
      - DB_PATH=/app/data/transcendaire.db

    networks:
      - transcendence
    restart: unless-stopped

  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile.dev
    container_name: transcendence-client-dev
    volumes:
      - ./client/src:/app/src:ro
      - client-build:/output
      - /app/node_modules
      - /app/public
    networks:
      - transcendence

volumes:
  client-build:
  dev-database:

networks:
  transcendence:
    driver: bridge
